app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

yeu_voyage_dashboard:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

#
# Routing partie gestion des traversées
#
yeu_voyage_traversee_index:
    path:      /traversee/
    defaults:  { _controller: AppBundle:Traversee:index }

yeu_voyage_traversee_detail_id:
    path:      /traversee/detail/
    defaults:  { _controller: AppBundle:Traversee:getTrajetById }
    options:
        expose: true

yeu_voyage_traversee_sauvegarder_nouveau_horaire:
    path:      /traversee/sauvegarder_horaires/
    defaults:  { _controller: AppBundle:Traversee:updateHoursTrajet }
    options:
        expose: true

yeu_voyage_traversee_annuler:
    path:      /traversee/annuler/
    defaults:  { _controller: AppBundle:Traversee:annulerTraversee }
    options:
        expose: true

yeu_voyage_traversee_activation_horaire_facultatif:
    path:      /traversee/activation_horaire/
    defaults:  { _controller: AppBundle:Traversee:activerHoraireFacultatif }
    options:
        expose: true

yeu_voyage_traversee_suppression_horaire_supplementaire:
    path:      /traversee/suppression_horaire_supplementaire/
    defaults:  { _controller: AppBundle:Traversee:supprimerHoraireSupplementaire }
    options:
        expose: true

yeu_voyage_traversee_retablir_horaire_modifie:
    path:      /traversee/retablir_horaire_modifie/
    defaults:  { _controller: AppBundle:Traversee:retablirHoraireModifie }
    options:
        expose: true

yeu_voyage_traversee_retablir_trajet:
    path:      /traversee/retablir_trajet/
    defaults:  { _controller: AppBundle:Traversee:retablirTrajet }
    options:
        expose: true

yeu_voyage_traversee_afficher:
    path:      /traversee/afficher/
    defaults:  { _controller: AppBundle:Traversee:afficher }

yeu_voyage_traversee_ajouter:
    path:      /traversee/ajouter/
    defaults:  { _controller: AppBundle:Traversee:ajouter }

yeu_voyage_traversee_importer:
    path:      /traversee/importer/
    defaults:  { _controller: AppBundle:Traversee:importer }

yeu_voyage_traversee_exporter:
    path:      /traversee/export/
    defaults:  { _controller: AppBundle:Traversee:export }

#
# Routing partie gestion des correspondances SNCF
#
yeu_voyage_correspondance_sncf_index:
    path:      /correspondance_sncf/
    defaults:  { _controller: AppBundle:CorrespondanceSncf:index }

yeu_voyage_correspondance_sncf_afficher:
    path:      /correspondance_sncf/afficher/
    defaults:  { _controller: AppBundle:CorrespondanceSncf:afficher }

yeu_voyage_correspondance_sncf_importer:
    path:      /correspondance_sncf/importer/
    defaults:  { _controller: AppBundle:CorrespondanceSncf:importer }

#
# Routing partie gestion des actualites
#
yeu_voyage_actualite_index:
    path:      /actualite/
    defaults:  { _controller: AppBundle:Actualite:index }

yeu_voyage_actualite_afficher:
    path:      /actualite/afficher/
    defaults:  { _controller: AppBundle:Actualite:afficher }

yeu_voyage_actualite_ajouter:
    path:      /actualite/ajouter/
    defaults:  { _controller: AppBundle:Actualite:ajouter }

yeu_voyage_actualite_supprimer:
    path:      /actualite/supprimer/
    defaults:  { _controller: AppBundle:Actualite:supprimerActualite }
    options:
        expose: true

yeu_voyage_actualite_detail:
    path:      /actualite/detail/
    defaults:  { _controller: AppBundle:Actualite:getActualiteById }
    options:
        expose: true

yeu_voyage_actualite_modifier:
    path:      /actualite/modifier/
    defaults:  { _controller: AppBundle:Actualite:modifierActualite }
    options:
        expose: true

#
# Routing partie gestion des compagnies
#
yeu_voyage_compagnie_afficher:
    path:      /compagnie/{compagnieId}
    defaults:  { _controller: AppBundle:Compagnie:afficher }

yeu_voyage_compagnie_modifier:
    path:      /compagnie/modifier/
    defaults:  { _controller: AppBundle:Compagnie:modifierCompagnie }
    options:
        expose: true

yeu_voyage_compagnie_fichier_supprimer:
    path:      /compagnie/fichier/supprimer/
    defaults:  { _controller: AppBundle:Compagnie:supprimerFichier }
    options:
        expose: true

yeu_voyage_compagnie_fichier_detail:
    path:      /compagnie/fichier/detail/
    defaults:  { _controller: AppBundle:Compagnie:detailFichier }
    options:
        expose: true

yeu_voyage_compagnie_fichier_modifier:
    path:      /compagnie/fichier/modifier/
    defaults:  { _controller: AppBundle:Compagnie:modifierFichier }
    options:
        expose: true

yeu_voyage_compagnie_bateau_detail:
    path:      /compagnie/bateau/detail/
    defaults:  { _controller: AppBundle:Compagnie:detailBateau }
    options:
        expose: true
#
# Routing partie gestion des parkings
#
yeu_voyage_parking_afficher:
    path:      /parking/afficher/
    defaults:  { _controller: AppBundle:Parking:afficher }

yeu_voyage_parking_ajouter:
    path:      /parking/ajouter/
    defaults:  { _controller: AppBundle:Parking:ajouter }

yeu_voyage_parking_supprimer:
    path:      /parking/supprimer/
    defaults:  { _controller: AppBundle:Parking:supprimerParking }
    options:
        expose: true

yeu_voyage_parking_detail:
    path:      /parking/detail/
    defaults:  { _controller: AppBundle:Parking:getParkingDetail }
    options:
        expose: true