AppBundle\Entity\Compagnie:
    type: entity
    table: yv_compagnie
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        telephone:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        mail:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        site:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    manyToMany:
        idGare:
            targetEntity: Gare
            cascade: {  }
            fetch: LAZY
            mappedBy: idCompagnie
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
