AppBundle\Entity\Ville:
    type: entity
    table: yv_ville
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        port:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
