AppBundle\Entity\YvAdminUser:
    type: entity
    table: yv_admin_user
    indexes:
        id_groupe:
            columns:
                - id_groupe
    uniqueConstraints:
        username:
            columns:
                - username
        email:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        entreprise:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        encryptedPassword:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
            column: encrypted_password
        salt:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        active:
            type: boolean
            nullable: false
            options:
                default: '0'
    manyToOne:
        idGroupe:
            targetEntity: YvAdminUserGroupe
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_groupe:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
