AppBundle\Entity\YvAdminConfig:
    type: entity
    table: yv_admin_config
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        numVersion:
            type: decimal
            nullable: false
            precision: 3
            scale: 1
            column: num_version
        afficherMessageAccueil:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: afficher_message_accueil
        titreMessageAccueil:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
            column: titre_message_accueil
        descriptionMessageAccueil:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: description_message_accueil
    lifecycleCallbacks: {  }
