AppBundle\Entity\YvRessource:
    type: entity
    table: yv_ressource
    indexes:
        id_compagnie:
            columns:
                - id_compagnie
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        url:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
    manyToOne:
        idCompagnie:
            targetEntity: Compagnie
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_compagnie:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
